### ISSUE TITLE
example file don't exist

### ISSUE THREAD

**Issue by Tolmino** [InstaPy2/InstaPy2#2]
hi
i'm watching your Instapy2 and i thank you for your time spending in this project....

some commits ago there was a example file that you have removed....
please can you give us an example file (a guide) to use Instapy2 functions ?

there is a way to add delays between actions ?

thanks in advance

**Comment by jarrodnorwell** [comment]
Hey @Tolmino,

I've cleaned the repository up a little to just include the code for the project.

All documentation (examples, guides, etc.) will be added to GitBook [here](https://official-antique.gitbook.io/instapy2).

Regards,
Antique

**Comment by jarrodnorwell** [comment]
Fixed by adding new documentation to README.
