### ISSUE TITLE
How do you use this? 

### ISSUE THREAD

**Issue by channelblackri** [InstaPy2/InstaPy2#26]

**Comment by jarrodnorwell** [comment]
@channelblackri I'm starting to add basic examples to the GitBook. The link can be found on the README.

**Comment by Seovtop** [comment]
> @channelblackri I'm starting to add basic examples to the GitBook. The link can be found on the README.

I got it for this example:

    session.comment(amount=10, iterable=[pk], type=CommentType.Locations)
**NameError: name 'CommentType' is not defined**

**Comment by jarrodnorwell** [comment]
Updated the example to fix that issue, line 2.

**Comment by Seovtop** [comment]
Result from example:
[INFO]: Found 10 of 10 valid media with the current configuration.

What next step? Just found)

**Comment by jarrodnorwell** [comment]
I didn't add any printing to comments, you may need to check your activity and I'll add that in the next update
