### ISSUE TITLE
How can I translate the Instapy template?

### ISSUE THREAD

**Issue by becauseimnoob** [InstaPy2/InstaPy2#27]
https://github.com/InstaPy/instapy-quickstart/blob/master/quickstart_templates/good_commenting_strategy_and_new_qs_system.py

**Comment by jarrodnorwell** [comment]
@becauseimnoob right now it's not possible to transfer everything over, especially with the rework branch. I'll start adding more features in the coming weeks/months if I'm free, sadly life and the need for money has gotten in the way more than it did before.
