### ISSUE TITLE
How do I start using the program?

### ISSUE THREAD

**Issue by lawyer88** [InstaPy2/InstaPy2#34]
Hi!
I could not find documentation on how to run the program - please help.
The installation stage has passed, but I can't figure out how to proceed, because I'm not a programmer: (
Please make the instructions and the "quick start" file to start the program, this will help many new users figure it out.
Thank you in advance, I'm really looking forward to the information!

**Comment by jarrodnorwell** [comment]
Hey @lawyer88,

I'm currently in the process of updating all of my repositories and will definitely look into adding a getting started script when I get to this repository.
