### ISSUE TITLE
Cant even run example script

### ISSUE THREAD

**Issue by marceloagoston** [InstaPy2/InstaPy2#36]
Hi, I tried to run the example script but I've got the following error:
```

Traceback (most recent call last):
  File "/home/maascg/Dev/PROYECTO/main.py", line 14, in <module>
    pk = session.configuration.location.get_pk(query='Resistencia')
         ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'InstaPy2' object has no attribute 'configuration'
```
Also I found lack of documentation... is the app currently working??  **I'm open to help to improve or fix it if you need help**

**Comment by khansaad1275** [comment]
> 

Facing same issues, i don't even know if this works or not. just throwing random errors. on top of that, this guy didn't even wrote a basic documentation.

**Comment by jarrodnorwell** [comment]
@marceloagoston yes it does still work, the limited documentation that does exist is a bit old (and bad) as I've moved onto emulation and application development.

`get_pk` is now a function of `InstaPy2` meaning `session.get_pk` is what needs to be used. I'll be rewriting the project this year and will add documentation along the way.

**Comment by marceloagoston** [comment]
Ahh okay thanks!! where I could find a little summary of functionalities like follow an account, get the list of users that follow an account, login, etc??

Remember, If you need help I could collaborate with this project
