### ISSUE TITLE
Noob needs help

### ISSUE THREAD

**Issue by OgHabibo** [InstaPy2/InstaPy2#38]
Instagram.py", line 11, in <module>
    pk = session.configuration.location.get_pk(query='place name here')
         ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'InstaPy2' object has no attribute 'configuration'

What can i put there? i dont understand it

**Comment by jarrodnorwell** [comment]
Hey @OgHabibo, I believe I've messed up the main branch and now that I'm working on the rewrite there's no point going back to fix main.

You are more than welcome to try the rewrite using pip install with the rewrite branch here which also has some working examples

**Comment by OgHabibo** [comment]
Thank you but this is my first python script i used so i dont have any knowledge
